# Generated by Django 3.0.5 on 2020-09-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='world', max_length=75)),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(default='media/def.jpeg', upload_to='media')),
                ('desc', models.TextField()),
            ],
        ),
    ]
