# Generated by Django 3.0.5 on 2020-09-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cnn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorylinks',
            name='serialNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
