# Generated by Django 3.0.5 on 2020-09-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20200831_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stories',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
