# Generated by Django 3.0.5 on 2020-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20200907_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='category',
            field=models.CharField(blank=True, default='world', max_length=75),
        ),
        migrations.AlterField(
            model_name='stories',
            name='image',
            field=models.ImageField(default='media/def.jpeg', upload_to='media'),
        ),
    ]
